require: rubocop-rspec

Metrics/CyclomaticComplexity:
  Exclude:
    - 'lib/qa/authorities/mesh_tools/mesh_data_parser.rb'

Metrics/ClassLength:
  Exclude:
    - 'lib/qa/authorities/linked_data/find_term.rb'
    - 'lib/qa/authorities/linked_data/search_query.rb'

RSpec/ExampleLength:
  Max: 7
  Exclude:
    - 'spec/lib/mesh_data_parser_spec.rb'
    - 'spec/lib/authorities/mesh_spec.rb'

RSpec/NamedSubject:
  Enabled: false
