# API documentation:
# http://www.oclc.org/developer/develop/web-services/fast-api/linked-data.en.html
term:
  url:                  http://id.worldcat.org/fast/__TERM_ID__/rdf.xml
  term_id:              ID                    # valid values:  ID | URI
  http_accept:          application/rdf+xml
  results:
    id_predicate:       http://purl.org/dc/terms/identifier
    label_predicate:    http://www.w3.org/2004/02/skos/core#prefLabel
    altlabel_predicate: http://www.w3.org/2004/02/skos/core#altLabel
    sameas_predicate:   http://schema.org/sameAs
search:
  url:                  http://experimental.worldcat.org/fast/search?query=__SUB_AUTH__+all+%22__QUERY__%22&sortKeys=usage&maximumRecords=__MAX_RECORDS__
  http_accept:          application/rdf+xml
  replacement_count:    1
  replacement_1:
    param:        maximumRecords
    pattern:      __MAX_RECORDS__
    default:      "20"
  results:
    id_predicate:       http://purl.org/dc/terms/identifier
    label_predicate:    http://www.w3.org/2004/02/skos/core#prefLabel
#    altlabel_predicate: http://www.w3.org/2004/02/skos/core#altLabel   # too long to be practical
    sort_predicate:     http://www.w3.org/2004/02/skos/core#prefLabel
  subauthorities:
    replacement:
      pattern:    __SUB_AUTH__
      default:    "cql.any"                   # Keywords in all headings
    topic:              oclc.topic             # Keywords in topical headings  (e.g. universities)
    geographic:         oclc.geographic        # Keywords in geographical headings  (e.g. ithaca)
    event_name:         oclc.eventName         # Keywords in event headings  (e.g. woodstock)
    personal_name:      oclc.personalName      # Keywords in personal headings  (e.g. george washington)
    corporate_name:     oclc.corporateName     # Keywords in corporate name headings  (e.g. cornell)
    uniform_title:      oclc.uniformTitle      # Keywords in uniform title headings (e.g. snow white)
    period:             oclc.period            # Keywords in period headings  (e.g. 1562)
    form:               oclc.form              # Keywords in form headings  (e.g. jazz)
    alt_lc:             oclc.altlc             # Keywords in LC Source headings  (e.g. gorilla)
#    lc_phrase:          oclc.lcphrase          # LC Source headings
#    lc_number:          oclc.lcnumber          # LCCN for LC Source Headings
#    heading:            oclc.heading           # Full headings
#    subphrase:          oclc.subphrase         # Subfield
#    see_also_phrase:    oclc.seeAlsophrase     # Full see also headings
#    identifier:         oclc.identifier        # FAST Authority Record Number (ARN)
#    faststatus:         oclc.faststatus        # Record status
#    establish:          oclc.establish         # Level of establishment
#    geocode:            oclc.geocode           # Geographic area code (GAC)
#    feature:            oclc.feature           # Geographic Feature
